export const leaveTypes = [
  { id: 1, code: 'CL', name: 'Casual Leave', unit: 'Days', status: 'ACTIVE' },
  { id: 2, code: 'ML', name: 'Medical Leave', unit: 'Days', status: 'ACTIVE' },
  { id: 3, code: 'EL', name: 'Earned Leave', unit: 'Days', status: 'ACTIVE' },
  { id: 4, code: 'VL', name: 'Vacation Leave', unit: 'Days', status: 'ACTIVE' },
]

export const demoProfiles = {
  employee: {
    id: 'EMP-1001',
    employee_id: 101,
    first_name: 'Rahul',
    last_name: 'Sharma',
    name: 'Rahul Sharma',
    email: 'rahul.sharma@college.edu',
    department: 'Computer Science',
    designation: 'Assistant Professor',
    category: 'Teaching - Non-Vacational',
    employee_category: 'Teaching - Non-Vacational',
    joining_date: '2021-07-15',
    status: 'ACTIVE',
    role: 'EMPLOYEE',
    department_id: 3,
  },
  hod: {
    id: 'HOD-2001',
    employee_id: 201,
    first_name: 'Ananya',
    last_name: 'Verma',
    name: 'Ananya Verma',
    email: 'ananya.verma@college.edu',
    department: 'Computer Science',
    designation: 'Professor & HoD',
    category: 'Teaching - Vacational',
    employee_category: 'Teaching - Vacational',
    joining_date: '2015-08-10',
    status: 'ACTIVE',
    role: 'DEPARTMENT_HEAD',
    department_id: 3,
  },
  admin: {
    id: 'ADM-3001',
    employee_id: 301,
    first_name: 'Naveen',
    last_name: 'Iyer',
    name: 'Naveen Iyer',
    email: 'naveen.iyer@college.edu',
    department: 'Administration',
    designation: 'Registrar',
    category: 'Non-Teaching / Administrative',
    employee_category: 'Non-Teaching / Administrative',
    joining_date: '2018-03-05',
    status: 'ACTIVE',
    role: 'ADMIN',
    department_id: 99,
  },
}

export const leaveBalances = [
  { leave_type_id: 1, leave_type: 'Casual Leave', entitled: 12, carry_forward: 2, used: 8, remaining: 6 },
  { leave_type_id: 2, leave_type: 'Medical Leave', entitled: 15, carry_forward: 0, used: 11, remaining: 4 },
  { leave_type_id: 3, leave_type: 'Earned Leave', entitled: 20, carry_forward: 3, used: 10, remaining: 13 },
]

export const employeeList = [
  { employee_id: 101, employee_code: 'EMP00101', name: 'Rahul Sharma', department: 'Computer Science', designation: 'Assistant Professor', category: 'Teaching - Non-Vacational', email: 'rahul.sharma@college.edu', status: 'ACTIVE' },
  { employee_id: 102, employee_code: 'EMP00102', name: 'Priya Nair', department: 'Computer Science', designation: 'Associate Professor', category: 'Teaching - Vacational', email: 'priya.nair@college.edu', status: 'ACTIVE' },
  { employee_id: 103, employee_code: 'EMP00103', name: 'Karan Patil', department: 'Mechanical Engineering', designation: 'Assistant Professor', category: 'Teaching - Non-Vacational', email: 'karan.patil@college.edu', status: 'ACTIVE' },
  { employee_id: 104, employee_code: 'EMP00104', name: 'Sonia Kapoor', department: 'Civil Engineering', designation: 'Professor', category: 'Teaching - Vacational', email: 'sonia.kapoor@college.edu', status: 'ACTIVE' },
  { employee_id: 105, employee_code: 'EMP00105', name: 'Vikram Singh', department: 'Administration', designation: 'Accountant', category: 'Non-Teaching / Administrative', email: 'vikram.singh@college.edu', status: 'INACTIVE' },
  { employee_id: 106, employee_code: 'EMP00106', name: 'Maya Iyer', department: 'Computer Science', designation: 'Lab Assistant', category: 'Vocational / Contractual', email: 'maya.iyer@college.edu', status: 'ACTIVE' },
]

export const applications = [
  {
    application_id: 125,
    employee_id: 101,
    employee_name: 'Rahul Sharma',
    leave_type: 'Casual Leave',
    leave_type_id: 1,
    start_date: '2026-09-15',
    end_date: '2026-09-17',
    requested_days: 3,
    calculated_days: 3,
    status: 'PENDING_DEPARTMENT_HEAD',
    submitted_at: '2026-09-07T10:30:00Z',
    reason: 'Family function',
    station_leaving: false,
    department: 'Computer Science',
  },
  {
    application_id: 126,
    employee_id: 102,
    employee_name: 'Priya Nair',
    leave_type: 'Medical Leave',
    leave_type_id: 2,
    start_date: '2026-09-10',
    end_date: '2026-09-13',
    requested_days: 4,
    calculated_days: 4,
    status: 'DEPARTMENT_APPROVED',
    submitted_at: '2026-09-02T09:00:00Z',
    reason: 'Consultation and rest',
    station_leaving: false,
    department: 'Computer Science',
  },
  {
    application_id: 127,
    employee_id: 103,
    employee_name: 'Karan Patil',
    leave_type: 'Earned Leave',
    leave_type_id: 3,
    start_date: '2026-09-20',
    end_date: '2026-09-27',
    requested_days: 8,
    calculated_days: 8,
    status: 'PENDING_ADMIN',
    submitted_at: '2026-09-05T11:15:00Z',
    reason: 'Travel and personal matters',
    station_leaving: true,
    department: 'Mechanical Engineering',
  },
  {
    application_id: 128,
    employee_id: 104,
    employee_name: 'Sonia Kapoor',
    leave_type: 'Vacation Leave',
    leave_type_id: 4,
    start_date: '2026-10-01',
    end_date: '2026-10-10',
    requested_days: 10,
    calculated_days: 10,
    status: 'ADMIN_APPROVED',
    submitted_at: '2026-08-27T08:20:00Z',
    reason: 'Academic break',
    station_leaving: true,
    department: 'Civil Engineering',
  },
  {
    application_id: 129,
    employee_id: 101,
    employee_name: 'Rahul Sharma',
    leave_type: 'Medical Leave',
    leave_type_id: 2,
    start_date: '2026-08-05',
    end_date: '2026-08-08',
    requested_days: 4,
    calculated_days: 4,
    status: 'ADMIN_REJECTED',
    submitted_at: '2026-07-28T15:45:00Z',
    reason: 'Health follow-up',
    station_leaving: false,
    department: 'Computer Science',
  },
  {
    application_id: 130,
    employee_id: 106,
    employee_name: 'Maya Iyer',
    leave_type: 'Casual Leave',
    leave_type_id: 1,
    start_date: '2026-09-25',
    end_date: '2026-09-26',
    requested_days: 2,
    calculated_days: 2,
    status: 'DEPARTMENT_REJECTED',
    submitted_at: '2026-09-03T16:10:00Z',
    reason: 'Personal obligation',
    station_leaving: false,
    department: 'Computer Science',
  },
]

export const alerts = [
  { id: 1, type: 'APPROACHING_LIMIT', severity: 'WARNING', title: 'Casual leave nearing threshold', message: 'You have used 8 of 12 casual leave days.', read: false, created_at: '2026-09-08T09:00:00Z' },
  { id: 2, type: 'PENDING_APPROVAL', severity: 'INFO', title: 'Awaiting department review', message: 'Application #LV-2026-00125 is pending department approval.', read: true, created_at: '2026-09-07T14:15:00Z' },
  { id: 3, type: 'APPLICATION_APPROVED', severity: 'SUCCESS', title: 'Leave approved', message: 'Your vacation leave has been approved by the admin.', read: false, created_at: '2026-09-06T11:20:00Z' },
  { id: 4, type: 'LIMIT_REACHED', severity: 'CRITICAL', title: 'Medical leave limit reached', message: 'You have reached your assigned medical leave entitlement.', read: false, created_at: '2026-09-05T07:40:00Z' },
]

export const dashboardStats = {
  totalApplications: 42,
  pendingApplications: 12,
  approvedLeaves: 18,
  rejectedApplications: 6,
  totalEmployees: 218,
  applicationsThisMonth: 31,
  pendingHodApproval: 9,
  pendingAdminApproval: 7,
  approvedThisMonth: 14,
  rejectedThisMonth: 5,
}

export const departmentBreakdown = [
  { name: 'Computer Science', value: 28 },
  { name: 'Mechanical', value: 19 },
  { name: 'Civil', value: 16 },
  { name: 'Administration', value: 11 },
  { name: 'Humanities', value: 7 },
]

export const monthlyTrend = [
  { month: 'Jan', applications: 18, leaveDays: 92 },
  { month: 'Feb', applications: 24, leaveDays: 114 },
  { month: 'Mar', applications: 21, leaveDays: 98 },
  { month: 'Apr', applications: 26, leaveDays: 118 },
  { month: 'May', applications: 30, leaveDays: 122 },
  { month: 'Jun', applications: 27, leaveDays: 133 },
]

export const leaveUsageByType = [
  { name: 'Casual', value: 34 },
  { name: 'Medical', value: 24 },
  { name: 'Earned', value: 28 },
  { name: 'Vacation', value: 14 },
]

export const holidays = [
  { date: '2026-10-02', title: 'Gandhi Jayanti', type: 'Holiday' },
  { date: '2026-11-14', title: 'Diwali', type: 'Holiday' },
  { date: '2026-12-25', title: 'Christmas', type: 'Holiday' },
  { date: '2027-01-26', title: 'Republic Day', type: 'Holiday' },
]
